In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('lgbm_importances_072465.csv')

In [4]:
df.head()

   Unnamed: 0        feature     importance  fold
0           0    ProductName       0.000000     1
1           1  EngineVersion  362268.572645     1
2           2     AppVersion  302730.508926     1
3           3   AvSigVersion  267867.776969     1
4           4         IsBeta       0.000000     1

In [5]:
cols = (df[["feature", "importance"]]
        .groupby("feature")
        .mean()
        .sort_values(by="importance", ascending=False)[:1000].index)

In [7]:
df.describe()

       Unnamed: 0    importance        fold
count  405.000000  4.050000e+02  405.000000
mean    40.000000  7.921401e+04    3.000000
std     23.409823  2.123182e+05    1.415963
min      0.000000  0.000000e+00    1.000000
25%     20.000000  9.742066e+02    2.000000
50%     40.000000  8.093515e+03    3.000000
75%     60.000000  5.344738e+04    4.000000
max     80.000000  1.667723e+06    5.000000

best_features = df.loc[df.feature.isin(cols)]

In [13]:
grdf = df[["feature", "importance"]].groupby("feature").mean().sort_values(by="importance", ascending=False)

In [32]:
unimportant = grdf[grdf['importance'] < 500]

In [35]:
list(unimportant.index)

['HasTpm',
 'Census_OSBuildNumber',
 'Census_IsPenCapable',
 'OsPlatformSubRelease',
 'Census_IsVirtualDevice',
 'Platform',
 'UacLuaenable',
 'Census_InternalBatteryType',
 'AutoSampleOptIn',
 'Census_IsFlightsDisabled',
 'ProductName',
 'Census_IsPortableOperatingSystem',
 'OsVer',
 'IsBeta',
 'Census_DeviceFamily']