In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('e32_lgbm_importances_073044.csv')

In [3]:
df.head()

   Unnamed: 0           feature     importance  fold
0           0     EngineVersion  410060.846752     1
1           1        AppVersion  326034.999458     1
2           2      AvSigVersion  479785.361422     1
3           3  RtpStateBitfield   30536.171169     1
4           4  IsSxsPassiveMode    5491.749016     1

In [4]:
cols = (df[["feature", "importance"]]
        .groupby("feature")
        .mean()
        .sort_values(by="importance", ascending=False)[:1000].index)

In [5]:
df.describe()

       Unnamed: 0    importance        fold
count  490.000000  4.900000e+02  490.000000
mean    34.500000  1.184260e+05    4.000000
std     20.225847  2.557460e+05    2.002044
min      0.000000  0.000000e+00    1.000000
25%     17.000000  2.558988e+03    2.000000
50%     34.500000  1.284832e+04    4.000000
75%     52.000000  1.059637e+05    6.000000
max     69.000000  1.725601e+06    7.000000

best_features = df.loc[df.feature.isin(cols)]

In [6]:
grdf = df[["feature", "importance"]].groupby("feature").mean().sort_values(by="importance", ascending=False)

In [11]:
unimportant = grdf[grdf['importance'] < 100]

In [12]:
list(unimportant.index)

['Census_InternalPrimaryDisplayResolutionHorizontal',
 'Census_InternalPrimaryDisplayResolutionVertical']