In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv('e34_lgbm_importances_073873.csv')

In [11]:
df.head()

   Unnamed: 0           feature    importance  fold
0           0     EngineVersion  1.059647e+06     1
1           1        AppVersion  8.904389e+05     1
2           2      AvSigVersion  3.300183e+06     1
3           3  RtpStateBitfield  1.018134e+05     1
4           4  IsSxsPassiveMode  1.580062e+04     1

In [12]:
cols = (df[["feature", "importance"]]
        .groupby("feature")
        .mean()
        .sort_values(by="importance", ascending=False)[:1000].index)

In [13]:
df.describe()

       Unnamed: 0    importance        fold
count  476.000000  4.760000e+02  476.000000
mean    33.500000  4.005904e+05    4.000000
std     19.648436  7.853555e+05    2.002104
min      0.000000  0.000000e+00    1.000000
25%     16.750000  1.297458e+04    2.000000
50%     33.500000  4.458937e+04    4.000000
75%     50.250000  3.818174e+05    6.000000
max     67.000000  3.764944e+06    7.000000

best_features = df.loc[df.feature.isin(cols)]

In [14]:
grdf = df[["feature", "importance"]].groupby("feature").mean().sort_values(by="importance", ascending=False)

In [15]:
unimportant = grdf[grdf['importance'] < 100]

In [16]:
list(unimportant.index)

['Census_IsAlwaysOnAlwaysConnectedCapable',
 'Census_ProcessorManufacturerIdentifier']